#pragma config(Motor,  port2,           rightDrive,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftDrive,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           rightDrive2,   tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           leftDrive2,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		{
			motor[leftDrive] = vexRT[Ch3];
			motor[leftDrive2] = vexRT[Ch3];
			motor[rightDrive] = vexRT[Ch2]; // There is a right drive motor that has a bad PWM cable connected to it, the connection
			motor[rightDrive2] = vexRT[Ch2]; // is bad in the middle where its soldered/heatshrinked together.

			if (vexRT[Btn6U] == 1)
			{
				motor[port6] = 127;
			}
			else
			{
				motor[port6] = 0;
			}
		}
	}
}
