#pragma config(Sensor, dgtl1,  rightDrive,     sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftDrive,      sensorQuadEncoder)
#pragma config(Motor,  port1,           mongoLeft,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftDrive1,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftDrive2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftDrive3,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftLift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightDrive3,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightDrive2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightDrive1,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          mongoRight,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	SensorValue[rightDrive] = 0;
	SensorValue[leftDrive] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

// Declaring functions for auton
void moveForward()
{
	motor[leftDrive1] = 127;
	motor[leftDrive2] = 127;
	motor[leftDrive3] = 127;
	motor[rightDrive3] = 127;
	motor[rightDrive2] = 127;
	motor[rightDrive1] = 127;
}

// Stop all drive motors
void stopDrive()
{
	motor[leftDrive1] = 0;
	motor[leftDrive2] = 0;
	motor[leftDrive3] = 0;
	motor[rightDrive3] = 0;
	motor[rightDrive2] = 0;
	motor[rightDrive1] = 0;
}

void rotateLeft()
{
	motor[leftDrive1] = -127;
	motor[leftDrive2] = -127;
	motor[leftDrive3] = -127;
	motor[rightDrive3] = 127;
	motor[rightDrive2] = 127;
	motor[rightDrive1] = 127;
}

void rotateRight()
{
	motor[leftDrive1] = 127;
	motor[leftDrive2] = 127;
	motor[leftDrive3] = 127;
	motor[rightDrive3] = -127;
	motor[rightDrive2] = -127;
	motor[rightDrive1] = -127;
}

void moveBackward()
{
	motor[leftDrive1] = -127;
	motor[leftDrive2] = -127;
	motor[leftDrive3] = -127;
	motor[rightDrive3] = -127;
	motor[rightDrive2] = -127;
	motor[rightDrive1] = -127;
}

void mongoUp()
{
	motor[mongoRight] = 127;
	motor[mongoLeft] = 127;
}

void mongoDown()
{
	motor[mongoRight] = -127;
	motor[mongoLeft] = -127;
}


void blueFlagSide()
{

}

void redFlagSide()
{

}

void blueFarSide()
{

}

void redFarSide()
{

}

task autonomous()
{
		//flag
	moveBackward();
	wait1Msec(1750);
	// Chooses which auton to run based on where jumper clips are placed
	if (vexRT[dgtl5] != vexRT[dgtl6] == 1)
	{
		blueFlagSide();
	}
	else if (vexRT[dgtl6] != vexRT[dgtl5] == 1)
	{
		redFlagSide();
	}
	else if (vexRT[dgtl6] && vexRT[dgtl5] == 1)
	{
		blueFarSide();
	}
	else if (vexRT[dgtl6] && vexRT[dgtl5] == 0)
	{
		redFarSide();
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// Declaring Variables
	int KpR = 0;
	int errorR = 0;
	int targetSpeedR = 0;
	int drivePowerR = 0;
	int KpL = 0;
	int errorL = 0;
	int targetSpeedL = 0;
	int drivePowerL = 0;
	bool brakes = false;

	while (true)
	{
		// Drive controls
		motor[rightDrive1] = vexRT[Ch2];
		motor[rightDrive2] = vexRT[Ch2];
		motor[rightDrive3] = vexRT[Ch2];
		motor[leftDrive1] = vexRT[Ch3];
		motor[leftDrive2] = vexRT[Ch3];
		motor[leftDrive3] = vexRT[Ch3];

		// Six bar controls
		if (vexRT[Btn6U] == 1)
		{
			motor[rightLift] = 127;
			motor[leftLift] = 127;
		}
		else if (vexRT[Btn6D] == 1)
		{
			motor[rightLift] = -127;
			motor[leftLift] = -127;
		}
		else
		{
			motor[rightLift] = 0;
			motor[leftLift] = 0;
		}

		// Four bar controls
		if (vexRT[Btn5U] == 1)
		{
			motor[mongoRight] = 127;
			motor[mongoLeft] = 127;
		}
		else if (vexRT[Btn5D] == 1)
		{
			motor[mongoRight] = -127;
			motor[mongoLeft] = -127;
		}
		else
		{
			motor[mongoRight] = 0;
			motor[mongoLeft] = 0;
		}

		// PID Parking Brake
		if (vexRT[Btn8D] == 1)
		{
			brakes = !brakes;
		}

		while (brakes == true)
		{
			// PID Parking Brake
			if (vexRT[Btn8D] == 1)
			{
				brakes = !brakes;
			}

			// Right side
			errorR = targetSpeedR - SensorValue[rightDrive];  // Currently just P, we can add on in the future
			drivePowerR += (int)(KpR*errorR);
			//
			// Limit the drive power range to 0
			//
			if (SensorValue[rightDrive] < drivePowerR)
			{
				while (SensorValue[rightDrive] < drivePowerR)
				{
					moveForward();
				}
				stopDrive();
			}
			else if (drivePowerR < 0)
			{
				drivePowerR = 0;
			}
			motor[rightDrive1] = drivePowerR;
			motor[rightDrive2] = drivePowerR;
			motor[rightDrive3] = drivePowerR;

			// Left side
			// PID Parking Brake left side
			errorL = targetSpeedL - SensorValue[leftDrive];   // Currently just P, we can add on in the future
			drivePowerL += (int)(KpL*errorL);
			//
			// Limit the drive power range to 0
			//
			if (drivePowerL > 0)
			{
				drivePowerL = 0;
			}
			else if (drivePowerL < 0)
			{
				drivePowerL = 0;
			}
			motor[leftDrive1] = drivePowerL;
			motor[leftDrive2] = drivePowerL;
			motor[leftDrive3] = drivePowerL;
		}
	}
}
