#pragma config(Sensor, in1,    autonPot,       sensorPotentiometer)
#pragma config(Sensor, in2,    platPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEnc,        sensorQuadEncoder)
#pragma config(Motor,  port1,           intake,        tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           puncher,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           midRight,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           backRight,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           adjuster,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           frontLeft,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           midLeft,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          backLeft,      tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "Auton PID.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	SensorValue(rightEnc) = 0;
	SensorValue(leftEnc) = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void intakeIn()
{
	motor[intake] = 127;
}

void intakeOut()
{
	motor[intake] = -127;
}

void shoot()
{
	motor[puncher] = 127;
	wait1Msec(1000);
	motor[puncher] = 0;
}

void pUp()
{
	motor[adjuster] = 127;
	wait1Msec(500);
	motor[adjuster] = 0;
}

void pDown()
{
	motor[adjuster] = -127;
	wait1Msec(500);
	motor[adjuster] = 0;
}

void liftUp()
{
	motor[lift] = 127;
}

void liftDown()
{
	motor[lift] = -127;
}

void stopAll()
{
	motor[intake] = 0;
	motor[lift] = 0;
	motor[adjuster] = 0;
	motor[puncher] = 0;
}

// Auton Functions

/***************************/
/*********RED NORTH*********/
/***************************/
void redNorth()
{
	if (platPot == true)
	{
		// Intake from under first cap
		moveStraight(37);
		intakeIn();
		wait1Msec(1000);

		// Shoot both middle flags
		moveTurn(-360);
		shoot();
		intakeIn();
		wait1Msec(500);
		stopAll();
		pUp();
		shoot();

		// Hit middle bottom flag the back up and aim for cap
		moveStraight(50);
		moveStraight(-27);
		moveTurn(-360);

		// Pull balls off of cap and intake them
		moveStraight(11);
		liftDown();
		wait1Msec(2000);
		stopAll();
		moveStraight(-6);
		intakeIn();
		wait1Msec(1000);

		// Flip cap and intake ball back in
		intakeOut();
		moveStraight(41);
		stopAll();
		intakeIn();
		wait1Msec(1000);
		stopAll();
		liftUp();
		wait1Msec(2000);
		stopAll();

		// Shoot red side flags
		moveTurn(360);
		shoot();
		intakeIn();
		wait1Msec(500);
		pDown();
		shoot();

		// Hit bottom flag while intaking
		intakeIn();
		moveStraight(50);
		stopAll();

		// Park on platform
		moveStraight(-72);
		moveTurn(360);
		moveStraight(36);
	}
	else
	{
		// Intake from under first cap
		moveStraight(37);
		intakeIn();
		wait1Msec(1000);

		// Shoot both middle flags
		moveTurn(-360);
		shoot();
		intakeIn();
		wait1Msec(500);
		stopAll();
		pUp();
		shoot();

		// Hit middle bottom flag the back up and aim for cap
		moveStraight(50);
		moveStraight(-27);
		moveTurn(-360);

		// Pull balls off of cap and intake them
		moveStraight(11);
		liftDown();
		wait1Msec(2000);
		stopAll();
		moveStraight(-6);
		intakeIn();
		wait1Msec(1000);

		// Flip cap and intake ball back in
		intakeOut();
		moveStraight(41);
		stopAll();
		intakeIn();
		wait1Msec(1000);
		stopAll();
		liftUp();
		wait1Msec(2000);
		stopAll();

		// Shoot red side flags
		moveTurn(360);
		shoot();
		intakeIn();
		wait1Msec(500);
		pDown();
		shoot();

		// Hit bottom flag while intaking
		intakeIn();
		moveStraight(50);
		stopAll();
	}
}

/***************************/
/*********RED SOUTH*********/
/***************************/
void redSouth()
{
	if (platPot == false)
	{
		// Intake ball from under first cap
		moveStraight(30);
		intakeIn();
		wait1Msec(1000);
		stopAll();
		moveStraight(3);

		// Shoot at far post then at middle post
		moveTurn(-180);
		shoot();
		intakeIn();
		moveTurn(-180);
		stopAll();
		shoot();

		// Back into wall to straighten out
		moveTurn(360);
		moveStraight(-24);
		moveTurn(-360);
		moveStraight(-28);

		// Pull balls off of blue cap and intake
		moveStraight(2);
		moveTurn(360);
		moveStraight(13);
		liftDown();
		wait1Msec(2000);
		moveStraight(-4);
		intakeIn();
		wait1Msec(2000);
		stopAll();

		// Flip cap
		liftUp();
		moveStraight(-3);
		stopAll();
		liftDown();
		wait1Msec(1000);
		moveStraight(7);
		liftUp();
		wait1Msec(2000);
		stopAll();

		// Park
		moveStraight(-2);
		moveTurn(-360);
		moveStraight(-4);
		moveStraight(36);
	}
	else
	{
		// Intake ball from under first cap
		moveStraight(30);
		intakeIn();
		wait1Msec(1000);
		stopAll();
		moveStraight(3);

		// Shoot at far post then at middle post
		moveTurn(-180);
		shoot();
		intakeIn();
		moveTurn(-180);
		stopAll();
		shoot();

		// Back into wall to straighten out
		moveTurn(360);
		moveStraight(-24);
		moveTurn(-360);
		moveStraight(-28);

		// Pull balls off of blue cap and intake
		moveStraight(2);
		moveTurn(360);
		moveStraight(13);
		liftDown();
		wait1Msec(2000);
		moveStraight(-4);
		intakeIn();
		wait1Msec(2000);
		stopAll();

		// Flip cap
		liftUp();
		moveStraight(-3);
		stopAll();
		liftDown();
		wait1Msec(1000);
		moveStraight(7);
		liftUp();
		wait1Msec(2000);
		stopAll();
	}
}

/****************************/
/*********BLUE NORTH*********/
/****************************/
void blueNorth()
{
	if (platPot == false)
	{
		// Intake from under first cap
		moveStraight(37);
		intakeIn();
		wait1Msec(1000);

		// Shoot both middle flags
		moveTurn(360);
		shoot();
		intakeIn();
		wait1Msec(500);
		stopAll();
		pUp();
		shoot();

		// Hit middle bottom flag the back up and aim for cap
		moveStraight(50);
		moveStraight(-27);
		moveTurn(360);

		// Pull balls off of cap and intake them
		moveStraight(11);
		liftDown();
		wait1Msec(2000);
		stopAll();
		moveStraight(-6);
		intakeIn();
		wait1Msec(1000);

		// Flip cap and intake ball back in
		intakeOut();
		moveStraight(41);
		stopAll();
		intakeIn();
		wait1Msec(1000);
		stopAll();
		liftUp();
		wait1Msec(2000);
		stopAll();

		// Shoot blue side flags
		moveTurn(-360);
		shoot();
		intakeIn();
		wait1Msec(500);
		pDown();
		shoot();

		// Hit bottom flag while intaking
		intakeIn();
		moveStraight(50);
		stopAll();

		// Park on platform
		moveStraight(-72);
		moveTurn(-360);
		moveStraight(36);
	}
	else
	{
		// Intake from under first cap
		moveStraight(37);
		intakeIn();
		wait1Msec(1000);

		// Shoot both middle flags
		moveTurn(360);
		shoot();
		intakeIn();
		wait1Msec(500);
		stopAll();
		pUp();
		shoot();

		// Hit middle bottom flag the back up and aim for cap
		moveStraight(50);
		moveStraight(-27);
		moveTurn(360);

		// Pull balls off of cap and intake them
		moveStraight(11);
		liftDown();
		wait1Msec(2000);
		stopAll();
		moveStraight(-6);
		intakeIn();
		wait1Msec(1000);

		// Flip cap and intake ball back in
		intakeOut();
		moveStraight(41);
		stopAll();
		intakeIn();
		wait1Msec(1000);
		stopAll();
		liftUp();
		wait1Msec(2000);
		stopAll();

		// Shoot blue side flags
		moveTurn(-360);
		shoot();
		intakeIn();
		wait1Msec(500);
		pDown();
		shoot();

		// Hit bottom flag while intaking
		intakeIn();
		moveStraight(50);
		stopAll();
	}
}

/****************************/
/*********BLUE SOUTH*********/
/****************************/
void blueSouth()
{
	if (platPot == false)
	{
		// Intake ball from under first cap
		moveStraight(30);
		intakeIn();
		wait1Msec(1000);
		stopAll();
		moveStraight(3);

		// Shoot at far post then at middle post
		moveTurn(180);
		shoot();
		intakeIn();
		moveTurn(180);
		stopAll();
		shoot();

		// Back into wall to straighten out
		moveTurn(-360);
		moveStraight(-24);
		moveTurn(360);
		moveStraight(-28);

		// Pull balls off of blue cap and intake
		moveStraight(2);
		moveTurn(-360);
		moveStraight(13);
		liftDown();
		wait1Msec(2000);
		moveStraight(-4);
		intakeIn();
		wait1Msec(2000);
		stopAll();

		// Flip cap
		liftUp();
		moveStraight(-3);
		stopAll();
		liftDown();
		wait1Msec(1000);
		moveStraight(7);
		liftUp();
		wait1Msec(2000);
		stopAll();

		// Park
		moveStraight(-2);
		moveTurn(360);
		moveStraight(-4);
		moveStraight(36);
	}
	else
	{
		// Intake ball from under first cap
		moveStraight(30);
		intakeIn();
		wait1Msec(1000);
		stopAll();
		moveStraight(3);

		// Shoot at far post then at middle post
		moveTurn(180);
		shoot();
		intakeIn();
		moveTurn(180);
		stopAll();
		shoot();

		// Back into wall to straighten out
		moveTurn(-360);
		moveStraight(-24);
		moveTurn(360);
		moveStraight(-28);

		// Pull balls off of blue cap and intake
		moveStraight(2);
		moveTurn(-360);
		moveStraight(13);
		liftDown();
		wait1Msec(2000);
		moveStraight(-4);
		intakeIn();
		wait1Msec(2000);
		stopAll();

		// Flip cap
		liftUp();
		moveStraight(-3);
		stopAll();
		liftDown();
		wait1Msec(1000);
		moveStraight(7);
		liftUp();
		wait1Msec(2000);
		stopAll();
	}
}

task autonomous()
{
	// Choose Auton
	if (autonPot == false)
	{
		blueNorth();
	}
	else if (false)
	{
		blueSouth();
	}
	else if (true)
	{
		redNorth();
	}
	else if (false)
	{
		redSouth();
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

// Included files
#include "Deadzone Drive.c";

task usercontrol()
{
	while (true)
	{
		// Starts tasks from Deadzone Drive.c
		startTask (rightDrive);
		startTask (leftDrive);

		if (vexRT(Btn8D) == 1)
		{
			motor[lift] = 127;
		}
		else if (vexRT(Btn7D) == 1)
		{
			motor[lift] = -127;
		}
		else
		{
			motor[lift] = 0;
		}

		if (vexRT(Btn5U) == 1)
		{
			motor[intake] = 127;
		}
		else if (vexRT(Btn5D) == 1)
		{
			motor[intake] = -127;
		}
		else
		{
			motor[intake] = 0;
		}

		if (vexRT(Btn6U) == 1)
		{
			motor[puncher] = 127;
		}
		else
		{
			motor[puncher] = 0;
		}

		if (vexRT(Btn8U) == 1)
		{
			motor[adjuster] = 127;
		}
		else if (vexRT(Btn8D) == 1)
		{
			motor[adjuster] = -127;
		}
		else
		{
			motor[adjuster] = 0;
		}
	}
}
