#pragma config(Sensor, dgtl1,  ultrasonic,     sensorSONAR_inch)
#pragma config(Sensor, dgtl9,  ,               sensorSONAR_inch)
#pragma config(Motor,  port1,           leftdrive,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightdrive,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int	threshold = 20;

	while (true)
	{
		if (vexRT[Btn8R] == 1)
		{
			while (true)
			{
				if (SensorValue [ultrasonic] > threshold){
					motor[port3] = -127;
					motor[port4] = 127;
				}
			}

			motor[port1] = 0;
			motor[port2] = 0;
			motor[port3] = 0;
			motor[port4] = 0;
			motor[port5] = 0;
			motor[port6] = 0;

			clearTimer(T2);
			while (time1[T2] < 1500)
			{
				motor[port3] = 127;
				motor[port4] = 127;
			}
			motor[port1] = 0;
			motor[port2] = 0;
			motor[port3] = 0;
			motor[port4] = 0;
			motor[port5] = 0;
			motor[port6] = 0;
		}
	}
}
