#pragma config(Motor,  port1,           driveleft,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           driveright,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           arm,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		// Code for the drive system motors
		motor[port4] = vexRT[Ch2];
		motor[port3] = vexRT[Ch3]/1.7;
		// Code for arm and claw
		if(vexRT[Btn6U] == 1) // Copy and paste this algorithm for any other buttons
		{
			motor[port2] = -127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[port2] = 127;
		}
		else
		{
			motor[port2] = 0;
		}

		if(vexRT[Btn5U] == 1)
		{
			motor[port1] = 127;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[port1]= -127;
		}
		else
		{
			motor[port1] = 0;
		}

		if(vexRT[Btn7U] == 1)
		{
			motor[port9] = -127;
			motor[port10] = -127;
		}
		else if(vexRT[Btn7D] == 1)
		{
			motor[port9] = 127;
			motor[port10] = 127;
		}
		else
		{
			motor[port9] = 0;
			motor[port10] = 0;
		}
	}
}
