#pragma config(Motor,  port9,           motor9,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		motor[port9] = vexRT[Ch2];
	}
}
