#pragma config(Motor,  port1,           rightDriveMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftDriveMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...

	// Folds arm and claw into resting position.

	motor[port2] = -90; // This section of code needs testing, will probably have to be redone
	motor[port3] = -90; // ***** MAKE SURE TO TEST THIS CODE IN A SEPERATE PROGRAM *****
	motor[port4] = -90;
	motor[port5] = -90;
	motor[port6] = -90;
	motor[port7] = -90;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

// Robot moves forward and unfolds it's arm and claw.

task autonomous() // This section of code needs to be redone: not useful
{                 // ***** MAKE SURE TO TEST THE NEW CODE IN A SEPERATE PROGRAM *****
	clearTimer(T1);
	while(time1[T1] < 6000)
	{
		motor[port1] = 127/1.5;
		motor[port10] = 127/1.5;
		motor[port2] = 90;
		motor[port3] = 90;
		motor[port4] = 90;
		motor[port5] = 90;
	}
	motor[port1] = 0;
	motor[port10] = 0;
	motor[port2] = 0;
	motor[port3] = 0;
	motor[port4] = 0;
	motor[port5] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		// Code for the drive system motors
		motor[port2] = vexRT[Ch2];
		motor[port1] = vexRT[Ch3];
		motor[port3] = vexRT[Ch4];
		motor[port4] = vexRT[Ch4];
		// Code for motors of all three sections of the arm
		if(vexRT[Btn6U] == 1) // Copy and paste this algorithm for any other buttons
		{
			motor[port5] = -127;
			motor[port6] = -127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[port5] = 127;
			motor[port6] = 127;
		}
		else
		{
			motor[port5] = 0;
			motor[port6] = 0;
		}

		if(vexRT[Btn5U] == 1)
		{
			motor[port7] = -127;
			motor[port8] = -127;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[port7] = 127;
			motor[port8] = 127;
		}
		else
		{
			motor[port7] = 0;
			motor[port8] = 0;
		}

		if(vexRT[Btn7U] == 1)
		{
			motor[port9] = -127;
			motor[port10] = -127;
		}
		else if(vexRT[Btn7D] == 1)
		{
			motor[port9] = 127;
			motor[port10] = 127;
		}
		else
		{
			motor[port9] = 0;
			motor[port10] = 0;
		}
	}
}
