#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           shoulderMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           shoulderMotorREVERSE, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           elbowMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           elbowMotorREVERSE, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           flipperMotor,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           flipperMotorREVERSED, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           frontMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          backMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...

	motor[port3] = -60;
	motor[port4] = -60;
	motor[port5] = -60;
	motor[port6] = -60;
	motor[port7] = -60;
	motor[port8] = -60;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	clearTimer(T1);
	while(time1[T1] < 6000)
	{
		motor[port1] = 127/1.5;
		motor[port2] = 127/1.5;
		motor[port3] = 60;
		motor[port4] = 60;
		motor[port5] = 60;
		motor[port6] = 60;
	}
	motor[port1] = 0;
	motor[port2] = 0;
	motor[port3] = 0;
	motor[port4] = 0;
	motor[port5] = 0;
	motor[port6] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		int threshold = 10;
		if(vexRT[Ch1] > threshold)
		{
			motor(rightMotor) = vexRT[Ch2];
			motor(leftMotor) = vexRT[Ch2];
		}
		else if(vexRT[Ch1] < -threshold)
		{
			motor(rightMotor) = vexRT[Ch2];
			motor(leftMotor) = vexRT[Ch2];
		}
		else if(vexRT[Ch3] > threshold)
		{
			motor(rightMotor) = vexRT[Ch3];
			motor(leftMotor) = vexRT[Ch3];
		}
		else if(vexRT[Ch3] < -threshold)
		{
			motor(rightMotor) = vexRT[Ch3];
			motor(leftMotor) = vexRT[Ch3];
		}
		else if(vexRT[Ch2] > threshold)
		{
			motor(rightMotor) = vexRT[Ch1];
			motor(leftMotor) = -vexRT[Ch1];
			motor(backMotor) = 0;
		}
		else if(vexRT[Ch2] < -threshold)
		{
			motor(rightMotor) = -vexRT[Ch1];
			motor(leftMotor) = vexRT[Ch1];
			motor(backMotor) = 0;
		}
		else if(vexRT[Ch4] > 0)
		{
			motor(backMotor) = vexRT[Ch4];
			motor(rightMotor) = 0;
			motor(leftMotor) = 0;
		}
		if(vexRT[Ch4] < -threshold)
		{
			motor(backMotor) = -vexRT[Ch4];
			motor(rightMotor) = 0;
			motor(leftMotor) = 0;
		}
		else
		{
			motor(rightMotor) = 0;
			motor(leftMotor) = 0;
			motor(backMotor) = 0;
		}

		if(vexRT[Btn5U] == 1)
		{
			motor(shoulderMotor) = 127;
			motor(shoulderMotorREVERSE) = 127;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor(shoulderMotor) = -127;
			motor(shoulderMotorREVERSE) = -127;
		}
		else
		{
			motor(shoulderMotor) = 0;
			motor(shoulderMotorREVERSE) = 0;
		}

		if(vexRT[Btn6U] == 1)
		{
			motor(elbowMotor) = 50;
			motor(elbowMotorREVERSE) = 50;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor(elbowMotor) = -50;
			motor(elbowMotorREVERSE) = -50;
		}
		else
		{
			motor(elbowMotor) = 0;
			motor(elbowMotorREVERSE) = 0;
		}

		if(vexRT[Btn7L] == 1)
		{
			motor(flipperMotor) = 60;
			motor(flipperMotorREVERSED) = 60;
		}
		else if(vexRT[Btn8R] == 1)
		{
			motor(flipperMotor) = -60;
			motor(flipperMotorREVERSED) = -60;
		}
		else
		{
			motor(flipperMotor) = 0;
			motor(flipperMotorREVERSED) = 0;
		}

	}
}
