#pragma config(Motor,  port7,           puncherRight,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           puncherLeft,   tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[port7] = 127;
motor[port8] = 127;
wait1Msec(900);
motor[port7] = 0;
motor[port8] = 0;
}
